remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-include-cache
  - jekyll-seo-tag

title: "David Amptmeijer"
description: "Environmental Scientist | Mercury Cycling | Aquatic Biogeochemistry"

header_pages:
  - cv.md
  - research.md
  - publications.md
  - projects.md
  - media.md

markdown: kramdown
