remote_theme: "mmistakes/minimal-mistakes@4.24.0"

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap

title: "David J. Amptmeijer"
description: "Marine biogeochemist studying mercury cycling and methylmercury bioaccumulation in aquatic ecosystems."

og_image: /images/WithPenguins2.jpg

academicons: true

markdown: kramdown

head_scripts:
  - https://cdn.jsdelivr.net/npm/academicons@1.9.4/css/academicons.min.css
