remote_theme: "mmistakes/minimal-mistakes@4.24.0"

sass:
  sass_dir: _sass    # default for Minimal Mistakes theme
  style: compressed  # optional, minifies CSS

plugins:
  - jekyll-include-cache
  - jekyll-seo-tag

title: "David Amptmeijer"
description: "Environmental Scientist | Mercury Cycling | Aquatic Biogeochemistry"

markdown: kramdown
